/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    HoverContainer: typeof import('./../src/components/common/HoverContainer.vue')['default']
    IconAntDesignKeyOutlined: typeof import('~icons/ant-design/key-outlined')['default']
    IconAntDesignLogoutOutlined: typeof import('~icons/ant-design/logout-outlined')['default']
    IconCustomVite: typeof import('~icons/custom/vite')['default']
    IconParkOutlineAlipay: typeof import('~icons/icon-park-outline/alipay')['default']
    IconParkOutlineApple: typeof import('~icons/icon-park-outline/apple')['default']
    IconParkOutlineTencentQq: typeof import('~icons/icon-park-outline/tencent-qq')['default']
    IconParkOutlineWechat: typeof import('~icons/icon-park-outline/wechat')['default']
    IconParkOutlineWeibo: typeof import('~icons/icon-park-outline/weibo')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemLogo: typeof import('./../src/components/common/SystemLogo.vue')['default']
  }
}
